
tinymce.addI18n('ar', {
  "Redo": "إعادة",
  "Undo": "تراجع",
  "Cut": "قص",
  "Copy": "نسخ",
  "Paste": "لصق",
  "Select all": "تحديد الكل",
  "New document": "مستند جديد",
  "Ok": "موافق",
  "Cancel": "إلغاء",
  "Visual aids": "مساعدات بصرية",
  "Bold": "عريض",
  "Italic": "مائل",
  "Underline": "تحته خط",
  "Strikethrough": "يتوسطه خط",
  "Superscript": "مرتفع",
  "Subscript": "منخفض",
  "Clear formatting": "إزالة التنسيق",
  "Align left": "محاذاة لليسار",
  "Align center": "محاذاة للوسط",
  "Align right": "محاذاة لليمين",
  "Justify": "ضبط",
  "Bullet list": "قائمة نقطية",
  "Numbered list": "قائمة رقمية",
  "Decrease indent": "تقليل المسافة البادئة",
  "Increase indent": "زيادة المسافة البادئة",
  "Close": "إغلاق",
  "Formats": "تنسيقات",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "متصفحك لا يدعم الوصول المباشر إلى الحافظة. يرجى استخدام اختصارات لوحة المفاتيح Ctrl+X/C/V بدلا من ذلك.",
  "Headers": "ترويسات",
  "Headings": "العناوين",
  "Heading 1": "عنوان 1",
  "Heading 2": "عنوان 2",
  "Heading 3": "عنوان 3",
  "Heading 4": "عنوان 4",
  "Heading 5": "عنوان 5",
  "Heading 6": "عنوان 6",
  "Preformatted": "منسق مسبقا",
  "Div": "Div",
  "Pre": "Pre",
  "Code": "كود",
  "Paragraph": "فقرة",
  "Blockquote": "اقتباس",
  "Inline": "مضمن",
  "Blocks": "كتل",
  "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "تم تفعيل وضع اللصق كنص عادي. سيتم الآن لصق المحتويات كنص عادي حتى تقوم بإيقاف تشغيل هذا الخيار.",
  "Fonts": "الخطوط",
  "Font Sizes": "أحجام الخط",
  "Class": "فئة",
  "Browse for an image": "تصفح بحثاً عن صورة",
  "OR": "أو",
  "Drop an image here": "إسقاط صورة هنا",
  "Upload": "رفع",
  "Block": "كتلة",
  "Align": "محاذاة",
  "Default": "افتراضي",
  "Circle": "دائرة",
  "Disc": "قرص",
  "Square": "مربع",
  "Lower Alpha": "أبجدي صغير",
  "Lower Greek": "يوناني صغير",
  "Lower Roman": "روماني صغير",
  "Upper Alpha": "أبجدي كبير",
  "Upper Roman": "روماني كبير",
  "Anchor": "مرساة",
  "Name": "الاسم",
  "Id": "المعرف",
  "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "يجب أن يبدأ المعرف بحرف، يليه فقط حروف أو أرقام أو شرطات أو نقاط أو أحرف أو شرطات سفلية.",
  "You have unsaved changes are you sure you want to navigate away?": "لديك تغييرات غير محفوظة هل أنت متأكد أنك تريد الانتقال بعيدا؟",
  "Restore last draft": "استعادة آخر مسودة",
  "Special character": "حرف خاص",
  "Source code": "كود المصدر",
  "Insert/Edit code sample": "إدراج/تحرير نموذج كود",
  "Language": "اللغة",
  "Code sample": "نموذج كود",
  "Color": "اللون",
  "R": "R",
  "G": "G",
  "B": "B",
  "Left to right": "من اليسار إلى اليمين",
  "Right to left": "من اليمين إلى اليسار",
  "Emoticons": "الرموز التعبيرية",
  "Document properties": "خصائص المستند",
  "Title": "العنوان",
  "Keywords": "الكلمات المفتاحية",
  "Description": "الوصف",
  "Robots": "الروبوتات",
  "Author": "المؤلف",
  "Encoding": "الترميز",
  "Fullscreen": "ملء الشاشة",
  "Action": "إجراء",
  "Shortcut": "اختصار",
  "Help": "مساعدة",
  "Address": "عنوان",
  "Focus to menubar": "التركيز على شريط القوائم",
  "Focus to toolbar": "التركيز على شريط الأدوات",
  "Focus to element path": "التركيز على مسار العنصر",
  "Focus to contextual toolbar": "التركيز على شريط الأدوات السياقي",
  "Insert link (if link plugin activated)": "إدراج رابط (إذا كان ملحق الرابط مفعلاً)",
  "Save (if save plugin activated)": "حفظ (إذا كان ملحق الحفظ مفعلاً)",
  "Find (if searchreplace plugin activated)": "بحث (إذا كان ملحق البحث والاستبدال مفعلاً)",
  "Plugins installed ({0}):": "الملحقات المثبتة ({0}):",
  "Premium plugins:": "الملحقات المتميزة:",
  "Learn more...": "تعلم المزيد...",
  "You are using {0}": "أنت تستخدم {0}",
  "Plugins": "الملحقات",
  "Handy Shortcuts": "اختصارات مفيدة",
  "Horizontal line": "خط أفقي",
  "Insert/edit image": "إدراج/تحرير صورة",
  "Image description": "وصف الصورة",
  "Source": "المصدر",
  "Dimensions": "الأبعاد",
  "Constrain proportions": "تقييد النسب",
  "General": "عام",
  "Advanced": "متقدم",
  "Style": "النمط",
  "Vertical space": "المساحة العمودية",
  "Horizontal space": "المساحة الأفقية",
  "Border": "الحدود",
  "Insert image": "إدراج صورة",
  "Image...": "صورة...",
  "Image list": "قائمة الصور",
  "Rotate counterclockwise": "دوران عكس عقارب الساعة",
  "Rotate clockwise": "دوران مع عقارب الساعة",
  "Flip vertically": "قلب عمودي",
  "Flip horizontally": "قلب أفقي",
  "Edit image": "تحرير الصورة",
  "Image options": "خيارات الصورة",
  "Zoom in": "تكبير",
  "Zoom out": "تصغير",
  "Crop": "اقتصاص",
  "Resize": "تغيير الحجم",
  "Orientation": "الاتجاه",
  "Brightness": "السطوع",
  "Sharpen": "حدة",
  "Contrast": "التباين",
  "Color levels": "مستويات اللون",
  "Gamma": "جاما",
  "Invert": "عكس",
  "Apply": "تطبيق",
  "Back": "رجوع",
  "Insert date/time": "إدراج التاريخ/الوقت",
  "Date/time": "التاريخ/الوقت",
  "Insert/Edit Link": "إدراج/تحرير رابط",
  "Insert/edit link": "إدراج/تحرير رابط",
  "Text to display": "النص المعروض",
  "Url": "عنوان URL",
  "Open link in...": "فتح الرابط في...",
  "Current window": "النافذة الحالية",
  "None": "لا شيء",
  "New window": "نافذة جديدة",
  "Remove link": "إزالة الرابط",
  "Anchors": "المراسي",
  "Link...": "رابط...",
  "Paste or type a link": "لصق أو كتابة رابط",
  "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "يبدو أن عنوان URL الذي أدخلته هو عنوان بريد إلكتروني. هل تريد إضافة البادئة mailto: المطلوبة؟",
  "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "يبدو أن عنوان URL الذي أدخلته هو رابط خارجي. هل تريد إضافة البادئة http:// المطلوبة؟",
  "Link list": "قائمة الروابط",
  "Insert video": "إدراج فيديو",
  "Insert/edit video": "إدراج/تحرير فيديو",
  "Insert/edit media": "إدراج/تحرير وسائط",
  "Alternative source": "مصدر بديل",
  "Alternative source URL": "عنوان URL للمصدر البديل",
  "Media poster (Image URL)": "ملصق الوسائط (عنوان URL للصورة)",
  "Paste your embed code below:": "لصق كود التضمين أدناه:",
  "Embed": "تضمين",
  "Media...": "وسائط...",
  "Nonbreaking space": "مسافة غير منقسمة",
  "Page break": "فاصل صفحة",
  "Paste as text": "لصق كنص",
  "Preview": "معاينة",
  "Print...": "طباعة...",
  "Save": "حفظ",
  "Find": "بحث",
  "Replace with": "استبدال بـ",
  "Replace": "استبدال",
  "Replace all": "استبدال الكل",
  "Previous": "السابق",
  "Next": "التالي",
  "Find and replace...": "بحث واستبدال...",
  "Could not find the specified string.": "تعذر العثور على السلسلة المحددة.",
  "Match case": "مطابقة الحالة",
  "Find whole words only": "البحث عن كلمات كاملة فقط",
  "Spell check": "تدقيق إملائي",
  "Ignore": "تجاهل",
  "Ignore all": "تجاهل الكل",
  "Finish": "إنهاء",
  "Add to Dictionary": "إضافة إلى القاموس",
  "Insert table": "إدراج جدول",
  "Table properties": "خصائص الجدول",
  "Delete table": "حذف الجدول",
  "Cell": "خلية",
  "Row": "صف",
  "Column": "عمود",
  "Cell properties": "خصائص الخلية",
  "Merge cells": "دمج الخلايا",
  "Split cell": "تقسيم الخلية",
  "Insert row before": "إدراج صف قبل",
  "Insert row after": "إدراج صف بعد",
  "Delete row": "حذف صف",
  "Row properties": "خصائص الصف",
  "Cut row": "قص الصف",
  "Copy row": "نسخ الصف",
  "Paste row before": "لصق الصف قبل",
  "Paste row after": "لصق الصف بعد",
  "Insert column before": "إدراج عمود قبل",
  "Insert column after": "إدراج عمود بعد",
  "Delete column": "حذف عمود",
  "Cols": "أعمدة",
  "Rows": "صفوف",
  "Width": "العرض",
  "Height": "الارتفاع",
  "Cell spacing": "تباعد الخلايا",
  "Cell padding": "حشوة الخلايا",
  "Show caption": "إظهار التسمية التوضيحية",
  "Left": "يسار",
  "Center": "وسط",
  "Right": "يمين",
  "Cell type": "نوع الخلية",
  "Scope": "النطاق",
  "Alignment": "المحاذاة",
  "H Align": "المحاذاة الأفقية",
  "V Align": "المحاذاة العمودية",
  "Top": "أعلى",
  "Middle": "وسط",
  "Bottom": "أسفل",
  "Header cell": "خلية رأس",
  "Row group": "مجموعة صفوف",
  "Column group": "مجموعة أعمدة",
  "Row type": "نوع الصف",
  "Header": "رأس",
  "Body": "جسم",
  "Footer": "تذييل",
  "Border color": "لون الحدود",
  "Insert template...": "إدراج قالب...",
  "Templates": "القوالب",
  "Template": "قالب",
  "Text color": "لون النص",
  "Background color": "لون الخلفية",
  "Custom...": "مخصص...",
  "Custom color": "لون مخصص",
  "No color": "بدون لون",
  "Remove color": "إزالة اللون",
  "Table of Contents": "جدول المحتويات",
  "Show blocks": "إظهار الكتل",
  "Show invisible characters": "إظهار الأحرف غير المرئية",
  "Word count": "عدد الكلمات",
  "Count": "العدد",
  "Document": "المستند",
  "Selection": "التحديد",
  "Words": "الكلمات",
  "Words: {0}": "الكلمات: {0}",
  "{0} words": "{0} كلمة",
  "File": "ملف",
  "Edit": "تحرير",
  "Insert": "إدراج",
  "View": "عرض",
  "Format": "تنسيق",
  "Table": "جدول",
  "Tools": "أدوات",
  "Powered by {0}": "مدعوم بواسطة {0}",
  "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "منطقة نص منسق. اضغط ALT-F9 للقائمة. اضغط ALT-F10 لشريط الأدوات. اضغط ALT-0 للمساعدة",
  "Image title": "عنوان الصورة",
  "Border width": "عرض الحدود",
  "Border style": "نمط الحدود",
  "Error": "خطأ",
  "Warn": "تحذير",
  "Valid": "صالح",
  "To open the popup, press Shift+Enter": "لفتح النافذة المنبثقة، اضغط Shift+Enter",
  "Rich Text Area. Press ALT-0 for help.": "منطقة نص منسق. اضغط ALT-0 للمساعدة.",
  "System Font": "خط النظام",
  "Failed to upload image: {0}": "فشل في تحميل الصورة: {0}",
  "Failed to load plugin: {0} from url {1}": "فشل في تحميل الملحق: {0} من عنوان URL {1}",
  "Failed to load plugin url: {0}": "فشل في تحميل عنوان URL للملحق: {0}",
  "Failed to initialize plugin: {0}": "فشل في تهيئة الملحق: {0}",
  "example": "مثال",
  "Search": "بحث",
  "All": "الكل",
  "Currency": "العملة",
  "Text": "النص",
  "Quotations": "اقتباسات",
  "Mathematical": "رياضي",
  "Extended Latin": "لاتيني موسع",
  "Symbols": "رموز",
  "Arrows": "أسهم",
  "User Defined": "معرف من قبل المستخدم",
  "dollar sign": "علامة الدولار",
  "currency sign": "علامة العملة",
  "euro-currency sign": "علامة عملة اليورو",
  "colon sign": "علامة النقطتين",
  "cruzeiro sign": "علامة كروزيرو",
  "french franc sign": "علامة الفرنك الفرنسي",
  "lira sign": "علامة الليرة",
  "mill sign": "علامة المليم",
  "naira sign": "علامة النيرة",
  "peseta sign": "علامة البيزيتا",
  "rupee sign": "علامة الروبية",
  "won sign": "علامة الوون",
  "new sheqel sign": "علامة الشيكل الجديد",
  "dong sign": "علامة الدونغ",
  "kip sign": "علامة الكيب",
  "tugrik sign": "علامة التوغروغ",
  "drachma sign": "علامة الدراخما",
  "german penny symbol": "رمز البنس الألماني",
  "peso sign": "علامة البيزو",
  "guarani sign": "علامة الغواراني",
  "austral sign": "علامة الأسترال",
  "hryvnia sign": "علامة الهريفنيا",
  "cedi sign": "علامة السيدي",
  "livre tournois sign": "علامة الليفر تورنوا",
  "spesmilo sign": "علامة سبيسميلو",
  "tenge sign": "علامة التينغي",
  "indian rupee sign": "علامة الروبية الهندية",
  "turkish lira sign": "علامة الليرة التركية",
  "nordic mark sign": "علامة المارك الاسكندنافي",
  "manat sign": "علامة المانات",
  "ruble sign": "علامة الروبل",
  "yen character": "حرف الين",
  "yuan character": "حرف اليوان",
  "yuan character, in hong kong and taiwan": "حرف اليوان، في هونغ كونغ وتايوان",
  "yen/yuan character variant one": "البديل الأول لحرف الين/اليوان",
  "Loading emoticons...": "جار تحميل الرموز التعبيرية...",
  "Could not load emoticons": "تعذر تحميل الرموز التعبيرية",
  "People": "الأشخاص",
  "Animals and Nature": "الحيوانات والطبيعة",
  "Food and Drink": "الطعام والشراب",
  "Activity": "النشاط",
  "Travel and Places": "السفر والأماكن",
  "Objects": "الأشياء",
  "Flags": "الأعلام",
  "Characters": "الأحرف",
  "Characters (no spaces)": "الأحرف (بدون مسافات)",
  "{0} characters": "{0} حرف",
  "Error: Form submit field collision.": "خطأ: تصادم حقل إرسال النموذج.",
  "Error: No form element found.": "خطأ: لم يتم العثور على عنصر نموذج.",
  "Update": "تحديث",
  "Color swatch": "عينة اللون",
  "Turquoise": "فيروزي",
  "Green": "أخضر",
  "Blue": "أزرق",
  "Purple": "أرجواني",
  "Navy Blue": "أزرق داكن",
  "Dark Turquoise": "فيروزي داكن",
  "Dark Green": "أخضر داكن",
  "Medium Blue": "أزرق متوسط",
  "Medium Purple": "أرجواني متوسط",
  "Midnight Blue": "أزرق منتصف الليل",
  "Yellow": "أصفر",
  "Orange": "برتقالي",
  "Red": "أحمر",
  "Light Gray": "رمادي فاتح",
  "Gray": "رمادي",
  "Dark Yellow": "أصفر داكن",
  "Dark Orange": "برتقالي داكن",
  "Dark Red": "أحمر داكن",
  "Medium Gray": "رمادي متوسط",
  "Dark Gray": "رمادي داكن",
  "Light Green": "أخضر فاتح",
  "Light Yellow": "أصفر فاتح",
  "Light Red": "أحمر فاتح",
  "Light Purple": "أرجواني فاتح",
  "Light Blue": "أزرق فاتح",
  "Dark Purple": "أرجواني داكن",
  "Dark Blue": "أزرق داكن",
  "Black": "أسود",
  "White": "أبيض",
  "Switch to or from fullscreen mode": "التبديل إلى أو من وضع ملء الشاشة",
  "Open help dialog": "فتح مربع حوار المساعدة",
  "history": "التاريخ",
  "styles": "الأنماط",
  "formatting": "التنسيق",
  "alignment": "المحاذاة",
  "indentation": "المسافة البادئة",
  "Font": "الخط",
  "Size": "الحجم",
  "More...": "المزيد...",
  "Select...": "تحديد...",
  "Preferences": "التفضيلات",
  "Yes": "نعم",
  "No": "لا",
  "Keyboard Navigation": "التنقل بلوحة المفاتيح",
  "Version": "الإصدار",
  "Anchor": "مرساة",
  "Special character": "حرف خاص",
  "Code sample": "نموذج كود",
  "Color": "اللون",
  "Emoticons": "الرموز التعبيرية",
  "Document properties": "خصائص المستند",
  "Image": "صورة",
  "Insert link": "إدراج رابط",
  "Target": "الهدف",
  "Link": "رابط",
  "Poster": "ملصق",
  "Media": "وسائط",
  "Print": "طباعة",
  "Prev": "السابق",
  "Find and replace": "بحث واستبدال",
  "Whole words": "كلمات كاملة",
  "Spellcheck": "تدقيق إملائي",
  "Caption": "تسمية توضيحية",
  "Insert template": "إدراج قالب"
});
