
// Arabic translation for TinyMCE
tinymce.addI18n('ar', {
  "Redo": "إعادة",
  "Undo": "تراجع",
  "Cut": "قص",
  "Copy": "نسخ",
  "Paste": "لصق",
  "Select all": "تحديد الكل",
  "New document": "مستند جديد",
  "Bold": "عريض",
  "Italic": "مائل",
  "Underline": "تحته خط",
  "Strikethrough": "يتوسطه خط",
  "Superscript": "مرتفع",
  "Subscript": "منخفض",
  "Clear formatting": "إزالة التنسيق",
  "Align left": "محاذاة لليسار",
  "Align center": "محاذاة للوسط",
  "Align right": "محاذاة لليمين",
  "Justify": "ضبط",
  "Bullet list": "قائمة نقطية",
  "Numbered list": "قائمة رقمية",
  "Decrease indent": "تقليل المسافة البادئة",
  "Increase indent": "زيادة المسافة البادئة",
  "Close": "إغلاق",
  "Formats": "تنسيقات",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "متصفحك لا يدعم الوصول المباشر إلى الحافظة. يرجى استخدام اختصارات لوحة المفاتيح Ctrl+X/C/V بدلا من ذلك.",
  "Headings": "العناوين",
  "Heading 1": "عنوان 1",
  "Heading 2": "عنوان 2",
  "Heading 3": "عنوان 3",
  "Heading 4": "عنوان 4",
  "Heading 5": "عنوان 5",
  "Heading 6": "عنوان 6",
  "Preformatted": "منسق مسبقا",
  "Div": "Div",
  "Pre": "Pre",
  "Code": "كود",
  "Paragraph": "فقرة",
  "Blockquote": "اقتباس",
  "Inline": "مضمن",
  "Link": "رابط",
  "Image": "صورة",
  "Insert": "إدراج",
  "Tools": "أدوات",
  "View": "عرض"
});
